version: '3'
services:
  app:
    build:
      context: .
    tty: true
    ports: 
      - "8888:8888"
    volumes:
    - ./data:/root/src/data
    - ./notebook:/root/src/notebook
    command: jupyter-lab --ip 0.0.0.0 --allow-root -b localhost --NotebookApp.token=''