version: '3'
services:
  app:
    build:
      context: .
      shm_size: '4gb'
    tty: true
    volumes:
      - ./code:/root/src/code/
    ports: 
      - "8501:8501"
    command: streamlit run ./code/app.py