version: '3'
services:
  streamlit:
    build:
      context: .
      shm_size: '3gb'
    tty: true
    volumes:
      - ./codes/:/root/src/codes/
      - ./model/:/root/src/model/
    ports: 
      - "8501:8501"
    command: streamlit run ./codes/app.py