version: '3'
services:
  app:
    build:
      context: .
      shm_size: '3gb'
    tty: true
    ports: 
      - "8888:8888"
    command: jupyter-lab --ip 0.0.0.0 --allow-root -b localhost --NotebookApp.token=''